### PR TITLE
Add firmware 1.14

### PR DESCRIPTION
**Pull request by martonbtoth**
This PR adds the original firmware version 1.14

### CODE REVIEW

**Comment by talktopag** [comment]
FYI: 1.14 is great and sorts out compatability with both my flash carts (EMS 64Mb, Everdrive Clone), unfortunately it introduces a harsh audible pop when previewing or playing tracks on LSDJ 9.4.0. I'd imagine a few users have this specific use case in mind. I've reached out to FP support on this issue.

**Comment by BASEDNWAH** [comment]
Is it makhowastaken who has been making the gameboy boot screen versions of the firmware? Would be great to get one for 1.14!

**Comment by makhowastaken** [comment]
I am aware of the new firmware. I do not yet have the patched version ready. I will upload at that time.

**Comment by MRiCEQB** [comment]
Any updates on this?
FP released another 1.14 yesterday marked as "Stable Version".
Would be great to have these modified.

**Pull request closed without merging**
